[project]
name = "xyf-competition-mvp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agent-client-protocol>=0.8.1",
    "fastapi>=0.135.1",
    "numpy>=2.4.3",
    "pandas>=2.3.3",
    "python-multipart>=0.0.22",
    "requests>=2.32.5",
    "streamlit>=1.55.0",
    "uvicorn>=0.42.0",
]

[project.scripts]
xyf-competition-mvp = "xyf_competition_mvp:main"

[build-system]
requires = ["uv_build>=0.10.7,<0.11.0"]
build-backend = "uv_build"
